### PR TITLE
Update to Cake 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.2 to work.

### CODE REVIEW

**Comment by devlead** [comment]
Hold this one upgrading to Cake.Testing 0.17.1

**Comment by devlead** [comment]
Done, ready for review. The failing GitLink is that a PR issue?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@devlead thank you for updating this!

**Comment by gep13** [comment]
Relates to #12

**Pull request merged**
